name: build

on:
  pull_request:
  push:
    paths-ignore:
    - "README.md"
    branches:
      - main
      - releases/*
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest,ubuntu-latest,macos-latest]
        lazarus-versions: [2.0.12]
    steps:
    - uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.2
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        include-packages: "Synapse 40.1"
    - name: Build the Main Application
      if: ${{ matrix.operating-system == 'windows-latest' }}
      run: | 
        lazbuild -B "project1.lpi"
        zip c project1-win64.zip project1.exe
    - name: Build the Main Application
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: | 
        lazbuild -B "project1.lpi"
        zip c project1-linux64.zip project1
    - name: Build the Main Application (macOS)
      if: ${{ matrix.operating-system == 'macos-latest' }}
      run: |
        lazbuild -B --ws=cocoa "project1.lpi"
        pkgbuild --install-location /Applications --component package
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Release.txt
          LICENSE
          *.zip
